In [4]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [7]:
# minimum dimensions 
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)

[[1 2 3 4 5]]


In [8]:
# 数据类型参数
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [9]:
import numpy as np 
dt = np.dtype(np.int32) 
print(dt)

int32


In [10]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [11]:
# 这会调整 ndarray 的大小
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print(a) 

[[1 2]
 [3 4]
 [5 6]]


In [12]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
# 均匀分布的数字数组
import numpy as np 
a = np.arange(20) 
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
# 这是一维数组
import numpy as np 
a = np.arange(24) 
a.ndim  

# now reshape it 
b = a.reshape(2,4,3) 
print(b) 
# b is having three dimensions

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [21]:
# 数组的 dtype 是 int8 (1 字节)
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print(x.itemsize)

1


In [22]:
# 数组的 dtype 现在是 float32（4 个字节）
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.float32) 
print(x.itemsize)

4


In [23]:
import numpy as np 
x = np.array([1,2,3,4,5]) 
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [24]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [33]:
# 五个零的数组。默认 dtype 是 float
import numpy as np 
x = np.zeros(5, dtype=int,order='F') 
print(x)

[0 0 0 0 0]


In [35]:
import numpy as np 
x = np.zeros((5,), dtype = np.int32) 
print(x)

[0 0 0 0 0]


In [36]:
# 自定义类型
import numpy as np 
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [38]:
# 五个一的数组。默认 dtype 是 float
import numpy as np 
x = np.ones(5,dtype=int) 
print(x)

[1 1 1 1 1]


In [40]:
# 将list列表转换为 ndarray
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
print(a)

[1 2 3]


In [41]:
# dtype is set 
import numpy as np 

x = [1,2,3]
a = np.asarray(x, dtype = float) 
print(a)

[1. 2. 3.]


In [42]:
#ndarray from tuple 
import numpy as np 

x = (1,2,3) 
a = np.asarray(x) 
print(a)

[1 2 3]


In [51]:
# ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5)] 
a = np.asarray(x,dtype=object) 
print(a)

[(1, 2, 3) (4, 5)]


In [52]:
# 使用range函数创建列表对象
import numpy as np 
list = range(5) 
print(list)

range(0, 5)


In [53]:
# 从list列表中获取迭代器对象
import numpy as np 
list = range(5) 
it = iter(list)  

# 使用迭代器创建ndarray
x = np.fromiter(it, dtype = float) 
print(x)

[0. 1. 2. 3. 4.]


In [56]:
# numpy.arange(start, stop, step, dtype)

# start和stop参数设置
import numpy as np 
x = np.arange(10,20,2) 
print(x)
# numpy.linspace(start, stop, num, endpoint, retstep, dtype)

x = np.linspace(10,20,5) 
print(x)


[10 12 14 16 18]
[10.  12.5 15.  17.5 20. ]


In [57]:
# numpy.logspace(start, stop, num, endpoint, base, dtype)

import numpy as np 
# 默认基数为 10
a = np.logspace(1.0, 2.0, num = 10) 
print(a)



[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [65]:
# set base of log space to 2 
import numpy as np 
a = np.logspace(1,10,num = 10, base = 2) 
print(a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [67]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Original array is:')
print(a)
print('\n')

print('Modified array is:')
for x in np.nditer(a):
   print(x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [70]:
# numpy.matlib.empty(shape, dtype, order)
import numpy.matlib 
import numpy as np 

print(np.matlib.empty((2,2))) 
# filled with random data



[[1. 2.]
 [3. 4.]]


In [72]:
import numpy.matlib 
import numpy as np 
print(np.matlib.zeros((2,2))) 

[[0. 0.]
 [0. 0.]]


In [73]:
import numpy.matlib 
import numpy as np 
print(np.matlib.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [74]:
import numpy.matlib 
import numpy as np 
print(np.matlib.eye(n = 3, M = 4, k = 0, dtype = float))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [75]:
import numpy.matlib 
import numpy as np 
print( np.matlib.identity(5, dtype = float))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [76]:
import numpy.matlib 
import numpy as np 
print( np.matlib.rand(3,3))

[[0.54863725 0.18770223 0.75942142]
 [0.00966356 0.13126671 0.50257354]
 [0.74623896 0.66741864 0.45125981]]
